# Generated by Django 4.0 on 2022-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchapp', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addres',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
